# Generated by Django 5.0.2 on 2024-03-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='old_card',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
