# Generated by Django 5.0.2 on 2024-03-18 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_profile_old_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='old_card',
            new_name='old_cart',
        ),
    ]
